const ids=['brandName','productName','productDescription','objective','location','targetCustomer','ageRange','offer','budget','problem','outcome','tone','landingPage'];const $=id=>document.getElementById(id);
let state={brief:{},strategy:null,copy:null,creative:null,reels:null,selectedCopy:null};

function brief(){return Object.fromEntries(ids.map(id=>[id,$(id).value.trim()]));}
function fillBrief(b){ids.forEach(id=>{if($(id)&&b[id]!==undefined)$(id).value=b[id]||' ';});}
function resetState(){state={brief:{},strategy:null,copy:null,creative:null,reels:null,selectedCopy:null};}
function showTab(name){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===name));if(name==='saved')renderSaved();if(name==='export')renderPreview();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));

function generateDemo(){
 const b=state.brief;
 state.strategy={objective:b.objective,audience:b.targetCustomer,positioning:b.productName+' helps '+b.targetCustomer+' move from '+(b.problem||'a current challenge')+' to '+(b.outcome||'a clear desired result'),message:'Lead with the customer problem, show the transformation, then present the offer and a simple CTA.',testing:['Problem-led message','Outcome-led message','Question-led hook']};
 state.copy=[1,2,3].map(n=>({name:'Ad '+n,hook:n===1?'Still struggling with '+(b.problem||'this problem')+'?':n===2?'Imagine achieving '+(b.outcome||'your desired result')+'.':'What would change if you could solve this today?',primaryText:'If you are a '+(b.targetCustomer||'customer')+', '+(b.productName||'this solution')+' is designed to help you '+(b.outcome||'reach your goal')+'. '+(b.offer||'Learn more today')+'.',headline:b.productName||'Discover the difference',description:b.offer||'Learn more',cta:'Learn More'}));
 state.creative=[['Image Ad','Clean single-image concept focused on the core customer problem and transformation.'],['Carousel','Card 1 problem → Card 2 insight → Card 3 solution → Card 4 offer → Card 5 CTA.'],['Instagram Story','9:16 sequence with a strong first-frame hook, short proof point and CTA.'],['Instagram Reel','15–30 second vertical video showing problem → turning point → solution → CTA.']].map(x=>({format:x[0],concept:x[1]}));
 state.reels=[1,2,3].map(n=>({title:'Reel '+n,hook:n===1?'Stop translating in your head before you speak.':n===2?'One small change can make your message clearer.':'What if your next meeting felt easier?',scenes:['Hook in first 2 seconds','Show the customer problem','Introduce '+b.productName,'Show desired outcome','CTA: Learn More']}));
 state.selectedCopy=state.copy[0].name;renderResults();
}
function renderResults(){
 $('strategyResult').innerHTML='<h3>Demo strategy generated</h3><div class="result-grid">'+Object.entries(state.strategy).map(([k,v])=>'<div class="result-card"><strong>'+esc(k)+'</strong><p>'+esc(Array.isArray(v)?v.join(' • '):v)+'</p></div>').join('')+'</div><small class="demo-badge">DEMO MODE — Claude API not connected</small>';
 renderCopy();renderCreative();renderReels();
}
function renderCopy(){
 $('copyResult').innerHTML='<div class="ad-list">'+state.copy.map((a,i)=>'<article class="ad-card '+(state.selectedCopy===a.name?'selected':'')+'"><h3>'+esc(a.name)+(state.selectedCopy===a.name?'<span class="selected-tag">Selected</span>':'')+'</h3><label><span class="field-title">Hook</span><textarea class="editable textarea copy-field" data-index="'+i+'" data-key="hook">'+esc(a.hook)+'</textarea></label><label><span class="field-title">Primary Text</span><textarea class="editable textarea copy-field" data-index="'+i+'" data-key="primaryText">'+esc(a.primaryText)+'</textarea></label><label><span class="field-title">Headline</span><input class="editable copy-field" data-index="'+i+'" data-key="headline" value="'+attr(a.headline)+'"></label><label><span class="field-title">Description</span><input class="editable copy-field" data-index="'+i+'" data-key="description" value="'+attr(a.description)+'"></label><label><span class="field-title">CTA</span><input class="editable copy-field" data-index="'+i+'" data-key="cta" value="'+attr(a.cta)+'"></label><div class="card-actions"><button class="secondary useCopyBtn" data-index="'+i+'">'+(state.selectedCopy===a.name?'✓ Selected':'Use This Version')+'</button><button class="secondary copyBtn" data-index="'+i+'">Copy Ad</button></div></article>').join('')+'</div><small class="demo-badge">DEMO MODE — editable sample output</small>';
 document.querySelectorAll('.copy-field').forEach(el=>el.oninput=()=>{state.copy[Number(el.dataset.index)][el.dataset.key]=el.value;});
 document.querySelectorAll('.useCopyBtn').forEach(btn=>btn.onclick=()=>{state.selectedCopy=state.copy[Number(btn.dataset.index)].name;renderCopy();});
 document.querySelectorAll('.copyBtn').forEach(btn=>btn.onclick=()=>{const a=state.copy[Number(btn.dataset.index)];navigator.clipboard?.writeText(Object.entries(a).map(([k,v])=>k+': '+v).join('\n'));$('status').textContent='Ad copied';});
}
function renderCreative(){$('creativeResult').innerHTML=state.creative.map((x,i)=>'<article class="creative-card"><h3>'+esc(x.format)+'</h3><p>'+esc(x.concept)+'</p><div class="card-actions"><button class="secondary creativeEdit" data-index="'+i+'">Edit</button><button class="secondary creativeUse" data-index="'+i+'">Use Idea</button></div></article>').join('')+'<small class="demo-badge">DEMO MODE — sample concepts</small>';document.querySelectorAll('.creativeEdit').forEach(btn=>btn.onclick=()=>{const i=Number(btn.dataset.index);const next=prompt('Edit the creative concept:',state.creative[i].concept);if(next!==null&&next.trim()){state.creative[i].concept=next.trim();renderCreative();}});document.querySelectorAll('.creativeUse').forEach(btn=>btn.onclick=()=>{$('status').textContent='Creative idea '+(Number(btn.dataset.index)+1)+' selected';});}
function renderReels(){$('reelsResult').innerHTML='<div class="ad-list">'+state.reels.map((r,i)=>'<article class="ad-card"><h3>'+esc(r.title)+'</h3><label><span class="field-title">Hook</span><textarea class="editable textarea reel-field" data-index="'+i+'" data-key="hook">'+esc(r.hook)+'</textarea></label><div class="field-title">Scenes</div><ol class="reel-scenes">'+r.scenes.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ol><button class="secondary copyReel" data-index="'+i+'">Copy Script</button></article>').join('')+'</div><small class="demo-badge">DEMO MODE — editable sample scripts</small>';document.querySelectorAll('.reel-field').forEach(el=>el.oninput=()=>state.reels[Number(el.dataset.index)][el.dataset.key]=el.value);document.querySelectorAll('.copyReel').forEach(btn=>btn.onclick=()=>{const r=state.reels[Number(btn.dataset.index)];navigator.clipboard?.writeText(r.title+'\nHook: '+r.hook+'\nScenes:\n- '+r.scenes.join('\n- '));$('status').textContent='Reel script copied';});}
function regenerate(type){if(!state.brief.productName){$('status').textContent='Generate a campaign first.';showTab('brief');return;}const b=state.brief;if(type==='strategy'){state.strategy.message='Test the customer problem, transformation and offer in separate messages. '+new Date().toLocaleTimeString();renderResults();}if(type==='copy'){state.copy=state.copy.map((a,i)=>({...a,name:'Ad '+(i+1)+' • New',hook:i===0?'What if '+(b.outcome||'the result you want')+' was easier to reach?':i===1?'You do not need to stay stuck with '+(b.problem||'this challenge')+'.':'Ready to take the next step?',primaryText:'A fresh angle for '+(b.targetCustomer||'your audience')+': '+(b.productName||'our solution')+' can help you '+(b.outcome||'move forward')+'.'}));state.selectedCopy=state.copy[0].name;renderCopy();}if(type==='creative'){state.creative=state.creative.map((x,i)=>({...x,concept:'Alternative concept '+(i+1)+': '+x.concept}));renderCreative();}if(type==='reels'){state.reels=state.reels.map((r,i)=>({...r,title:'Reel '+(i+1)+' • New',hook:i===0?'Here is a simple way to '+(b.outcome||'get a better result')+'.':r.hook}));renderReels();}$('status').textContent='New '+type+' ideas generated';}
$('generate').onclick=()=>{state.brief=brief();if(!state.brief.brandName||!state.brief.productName||!state.brief.targetCustomer){$('status').textContent='Enter brand, product/service and target customer.';return;}generateDemo();$('status').textContent='Demo campaign generated';showTab('strategy');};
$('regenStrategy').onclick=()=>regenerate('strategy');$('regenCopy').onclick=()=>regenerate('copy');$('regenCreative').onclick=()=>regenerate('creative');$('regenReels').onclick=()=>regenerate('reels');
$('save').onclick=()=>{const b=brief();if(!b.productName){$('status').textContent='Enter a product/service first.';return;}const items=JSON.parse(localStorage.getItem('aiAdsCampaigns')||'[]');items.unshift({id:Date.now(),savedAt:new Date().toISOString(),brief:b,state});localStorage.setItem('aiAdsCampaigns',JSON.stringify(items.slice(0,50)));$('status').textContent='Campaign saved';};
$('newCampaign').onclick=()=>{if(confirm('Start a new campaign? Unsaved changes will be cleared.')){ids.forEach(id=>$(id).value='');resetState();$('strategyResult').innerHTML='<div class="placeholder">Complete the brief and generate a strategy.</div>';$('copyResult').innerHTML='<div class="placeholder">Generate a campaign to create ad copy.</div>';$('creativeResult').innerHTML='<article><h3>Image Ad</h3><p>Visual concept and text hierarchy.</p></article><article><h3>Carousel</h3><p>Problem → solution → proof → CTA.</p></article><article><h3>Story</h3><p>Vertical 9:16 concept.</p></article><article><h3>Reel</h3><p>Scene-by-scene creative concept.</p></article>';$('reelsResult').innerHTML='<div class="placeholder">Generate a campaign to create reel scripts.</div>';$('status').textContent='New campaign ready';showTab('brief');}};
$('clear').onclick=()=>$('newCampaign').click();
$('exportJson').onclick=()=>download('ai-ads-campaign.json',JSON.stringify(state,null,2),'application/json');$('exportText').onclick=()=>download('ai-ads-campaign.txt',Object.entries(brief()).map(([k,v])=>k+': '+v).join('\n'),'text/plain');
function renderSaved(){const items=JSON.parse(localStorage.getItem('aiAdsCampaigns')||'[]');$('savedList').innerHTML=items.length?items.map(x=>'<div class="saved-card"><div class="saved-meta"><strong>'+esc(x.brief.productName||'Untitled campaign')+'</strong><small>'+esc(x.brief.brandName||'')+' · '+new Date(x.savedAt).toLocaleString()+'</small></div><div class="saved-actions"><button class="secondary loadBtn" data-id="'+x.id+'">Load</button><button class="secondary danger deleteBtn" data-id="'+x.id+'">Delete</button></div></div>').join(''):'<div class="placeholder">No saved campaigns yet.</div>';document.querySelectorAll('.loadBtn').forEach(btn=>btn.onclick=()=>loadCampaign(Number(btn.dataset.id)));document.querySelectorAll('.deleteBtn').forEach(btn=>btn.onclick=()=>deleteCampaign(Number(btn.dataset.id)));}
function loadCampaign(id){const items=JSON.parse(localStorage.getItem('aiAdsCampaigns')||'[]');const item=items.find(x=>x.id===id);if(!item)return;fillBrief(item.brief);state=item.state||{brief:item.brief,strategy:null,copy:null,creative:null,reels:null,selectedCopy:null};if(!state.copy)generateDemo();else{renderResults();}state.brief=item.brief;$('status').textContent='Saved campaign loaded';showTab('strategy');}
function deleteCampaign(id){const items=JSON.parse(localStorage.getItem('aiAdsCampaigns')||'[]').filter(x=>x.id!==id);localStorage.setItem('aiAdsCampaigns',JSON.stringify(items));renderSaved();}
function renderPreview(){$('preview').textContent=JSON.stringify(state,null,2);}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function attr(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}